### ISSUE TITLE
Le favicon par défaut est actuellement celui d'Angular

### ISSUE THREAD

**Issue by demarsx** [nioperas06/benintechjobs#5]
Je pense que le favicon par défaut devrait être changé pour donner plus d'identité au site web. J'ai joint un exemple de favicon à mon post. 

![favicon](https://user-images.githubusercontent.com/5084657/38141632-f8faf66c-3430-11e8-9469-68caeca2ca02.png)

**Comment by nioperas06** [comment]
Merci pour ton aide. favicon rajouté :fire: !
